#!/bin/bash

usage() {
  echo -e "Usage:
  $0
  -t <pivnet-token>, PIVNET_TOKEN
  -o <opsman-url>, OM_TARGET
  -u <opsman-user>, OM_USERNAME
  -p <opsman-pass>, OM_PASSWORD
  -s <product-slug (optional, will enter interactive mode if not provided)>
  -r <release (optional, will enter interactive mode if not provided)>
  -i <id (optional)> \n" >&2; exit 1; }

checkcmds () {
  echo "Checking for installed scripts"

  if ! hash jq 2>/dev/null; then
    echo "Please install the latest jq as it could not be found."
    exit 1
  fi

  if ! hash pivnet 2>/dev/null; then
    echo "Please install the latest pivnet cli as it could not be found."
    exit 1
  fi

  if ! hash om 2>/dev/null; then
    echo "Please install the latest om cli as it could not be found."
    exit 1
  fi
}

login (){
  pivnet login --api-token="${PIVNET_TOKEN}"
}

om-upload () {
  om -target $OM_TARGET --skip-ssl-validation -u "${OM_USERNAME}" -p "${OM_PASSWORD}" upload-product --product "${STRIPPED_OBJECT_KEY}".pivotal
}

summary() {
  om -target $OM_TARGET --skip-ssl-validation -u "${OM_USERNAME}" -p "${OM_PASSWORD}" available-products
}

download-pivnet() {
  JSON=`pivnet product-files -p $SLUG -r $RELEASE --format=json`

  if [ -z "$PRODUCTID" ]; then
    PRODUCTID=$(echo $JSON | jq '.[] | select(.file_type =="Software").id')

    if [[ $PRODUCTID = *[[:space:]]* ]]; then
      echo "Sorry, found multiple IDs for ${SLUG}."
      echo
      idRetVal=$(pivnet product-files -p $SLUG -r $RELEASE --format json)
      echo $idRetVal | jq -r '["ID","NAME","VERSION"], ["--","----","-------"], (.[] | [.id, .name, .file_version]) | @csv' | tr -d '"' | column -ts ","
      echo
      echo "=> Please choose one and provide the id:"
      read PRODUCTID
    fi
  fi

  echo
  echo "✓ Will download $SLUG with release $RELEASE ($PRODUCTID)."
  
  pivnet download-product-files -p $SLUG -r $RELEASE -i $PRODUCTID --accept-eula

  AWS_OBJECT_KEY=$(echo $JSON | jq ".[] | select(.file_type ==\"Software\" and .id == ${PRODUCTID}).aws_object_key")

  OBJECT_KEY=${AWS_OBJECT_KEY##*/}
  STRIPPED_OBJECT_KEY=${OBJECT_KEY%.*}
}

check-slug-release() {
  if [ -z "$SLUG" ]; then
    echo "Here's a list of available products:"
    echo
    slugRetVal=$(pivnet products --format json)
    echo $slugRetVal | jq -r '["NAME","SLUG"], ["----","----"], (.[] | [.name, .slug]) | @csv' | tr -d '"' | column -ts ","
    echo
    echo "=> Please choose one and provide the slug:"
    read SLUG

    checkSlug=$( echo $slugRetVal | jq "[.[] |.slug == \"${SLUG}\"] | any")

    if ! $checkSlug ; then
      echo "Sorry, could not find provided slug. Are you sure you spelled it correctly?"
      exit 1
    fi

    echo
    echo "✓ Will upload $SLUG"
  fi

  if [ -z "$RELEASE" ]; then
    echo "Searching for available releases..."
    releaseRetVal=$(pivnet releases -p $SLUG --format json)

    echo "Here's what I found on network.pivotal.io:"
    echo
    echo $releaseRetVal | jq -r '["VERSION","DESCRIPTION"], ["-------","-----------"], (.[] | [.version, .description]) | @csv' | tr -d '"' | column -ts ","
    echo
    echo "=> Please choose one and provide the version:"
    read RELEASE
    echo
    echo "✓ Will upload $SLUG with release $RELEASE."
  fi
}

if (($# == 0))
then
  usage
fi

while getopts ":t:o:u:p:s:r:i:h" opt; do
  case $opt in
    t) PIVNET_TOKEN=$OPTARG
      ;;
    o) OM_TARGET=$OPTARG
      ;;
    u) OM_USERNAME=$OPTARG
      ;;
    p) OM_PASSWORD=$OPTARG
      ;;
    s) SLUG=$OPTARG
      ;;
    r) RELEASE=$OPTARG
      ;;
    i) PRODUCTID=$OPTARG
      ;;
    h) usage
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

checkcmds
login
check-slug-release
download-pivnet
om-upload
summary
